### ISSUE TITLE
Repo address in ArtifactHub is no longer valid

### ISSUE THREAD

**Issue by phil-flip** [my0n/helm-charts#15]
They still link to https://my0n.github.io/helm-charts, which unfortunately doesn't exist.

**Comment by phil-flip** [comment]
nvm.. RTFM

**Comment by my0n** [comment]
ah, sorry, i haven't really had time to homelab recently... probably not going to get back to this any time soon

these charts are so out of date that you're likely better off making your own or forking or whatever (thx for the interest tho)

**Comment by phil-flip** [comment]
No, the link is working fine, I was just doing it wrong.
Unless this is an issue from the helm side of things, it shouldn't matter, because they don't really change much on their infrastructure. The only issue I'm having right now is trying to get it to run in TrueNAS Scale.
